import { useState } from 'react';
import type { Visual } from './types';

/** Conceptual teaching aids. These diagrams never supply experiment evidence or simulator results. */
export default function ConceptVisual({ kind }: { kind: Visual }) {
  const [alternate, setAlternate] = useState(false);
  const [q0, setQ0] = useState(0);
  const [q1, setQ1] = useState(0);
  return <figure className="foundation-visual">
    <figcaption>CONCEPT SKETCH · NOT A SIMULATOR RESULT</figcaption>
    {kind === 'bit' && <><div className="foundation-bit"><span className="foundation-token">{alternate ? 1 : 0}</span><span>means</span><strong>{alternate ? 'Door open' : 'Door closed'}</strong></div><button aria-pressed={alternate} onClick={() => setAlternate(!alternate)}>Change the stored bit</button><p>Two agreed labels. One recorded answer.</p></>}
    {kind === 'basis' && <div className="foundation-pair-cards"><div><strong>|0⟩</strong><span>Prepare state zero</span><b>Read 0 with certainty</b></div><div><strong>|1⟩</strong><span>Prepare state one</span><b>Read 1 with certainty</b></div></div>}
    {kind === 'shots' && <><ol className="foundation-flow"><li><strong>Prepare</strong><span>Start again in |0⟩</span></li><li><strong>Apply gates</strong><span>Same circuit each time</span></li><li><strong>Measure</strong><span>Record one outcome</span></li></ol><p>Repeat this whole sequence for every shot. Tally the outcomes to get counts.</p></>}
    {(kind === 'signs' || kind === 'global') && <><div className="foundation-pair-cards"><div><span>Amplitude for |0⟩</span><strong>{kind === 'global' && alternate ? '−' : '+'}1/√2</strong><b>Squared magnitude: 1/2</b></div><div><span>Amplitude for |1⟩</span><strong>{alternate ? '−' : '+'}1/√2</strong><b>Squared magnitude: 1/2</b></div></div><button aria-pressed={alternate} onClick={() => setAlternate(!alternate)}>{kind === 'global' ? 'Reverse both signs' : 'Reverse only the one amplitude'}</button><p role="status">{kind === 'global' ? 'Both amplitudes change together. Their relative sign stays the same; every physical prediction is unchanged.' : alternate ? 'Opposite signs, still equal immediate probabilities. A later H can reveal this relative difference.' : 'Matching signs, equal probabilities. Now reverse one sign and compare.'}</p></>}
    {kind === 'interference' && <><div className="foundation-toggle" role="group" aria-label="Compare interference rules"><button aria-pressed={!alternate} onClick={() => setAlternate(false)}>H → H</button><button aria-pressed={alternate} onClick={() => setAlternate(true)}>H → Z → H</button></div><p>Contributions at the final H, after its division by √2:</p><div className="foundation-pair-cards"><div><span>Toward |0⟩</span><strong>{alternate ? '½ − ½ = 0' : '½ + ½ = 1'}</strong><b>{alternate ? 'Cancel → 0% chance' : 'Reinforce → 100% chance'}</b></div><div><span>Toward |1⟩</span><strong>{alternate ? '½ + ½ = 1' : '½ − ½ = 0'}</strong><b>{alternate ? 'Reinforce → 100% chance' : 'Cancel → 0% chance'}</b></div></div><p>These are worked arithmetic examples. Your collected trace tests the predictions using Qiskit.</p></>}
    {kind === 'pairs' && <><p>Build a basis label. The top wire q0 is the rightmost digit.</p><div className="foundation-toggle"><button onClick={() => setQ1(1 - q1)} aria-label={`Change q1, currently ${q1}`}>q1 = {q1}</button><button onClick={() => setQ0(1 - q0)} aria-label={`Change q0, currently ${q0}`}>q0 = {q0}</button></div><p className="foundation-pair-label" role="status">|{q1}{q0}⟩</p><p>Left: q1 = {q1}. Right: q0 = {q0}.</p></>}
    {kind === 'cx' && <><table className="foundation-table"><caption>CX with control q0 and target q1 · labels q1 q0</caption><thead><tr><th scope="col">Input</th><th scope="col">Control q0</th><th scope="col">Output</th></tr></thead><tbody>{['00', '01', '10', '11'].map((label) => <tr key={label}><th scope="row">|{label}⟩</th><td>{label[1]} · {label[1] === '1' ? 'flip q1' : 'leave q1'}</td><td>|{label[1] === '1' ? `${1 - Number(label[0])}1` : label}⟩</td></tr>)}</tbody></table><p>This rule applies to each basis component; it does not read the control.</p></>}
    {kind === 'bell' && <><ol className="foundation-flow"><li><strong>|00⟩</strong><span>Both start at zero</span></li><li><strong>H on q0</strong><span>00 and 01 contribute</span></li><li><strong>CX q0 → q1</strong><span>00 and 11 contribute</span></li></ol><p>One joint amplitude list connects the two qubits.</p></>}
    {kind === 'mixed' && <><div className="foundation-pair-cards"><div><strong>Pair together</strong><span>One pure Bell state</span><b>Joint purity 1</b></div><div><strong>Either part alone</strong><span>Maximally mixed</span><b>Reduced purity 0.5</b></div></div><p>The two local views omit the relationship in the joint state. They are not two independent pure qubits.</p></>}
  </figure>;
}
