import type { Question } from '../content';
import type { ExperimentDefinition, FoundationId, FoundationLesson } from './types';

const question = (id: string, prompt: string, options: string[], correct: number, explanation: string): Question => ({
  id, prompt, options, correct, feedback: options.map((_, i) => `${i === correct ? 'Exactly. ' : 'Revisit this idea. '}${explanation}`),
});
const predict = (id: string, prompt: string, correct: number, pairs = false): Question => ({
  id, prompt, options: pairs ? ['Only 00', 'Half 00 and half 11', 'All four pairs equally', 'I’m not sure'] : ['Always 0', 'Half 0 and half 1', 'Always 1', 'I’m not sure'],
  correct, feedback: Array(4).fill('Prediction recorded. Build the circuit and compare your prediction with the real ideal probabilities. A prediction earns credit for thinking, even if it changes after the experiment.'),
});
const a = Math.SQRT1_2;
const zero = { amplitudes: [1, 0], bloch: [[0, 0, 1] as [number, number, number]] };
const plus = { amplitudes: [a, a], bloch: [[1, 0, 0] as [number, number, number]] };
const minus = { amplitudes: [a, -a], bloch: [[-1, 0, 0] as [number, number, number]] };
const one = { amplitudes: [0, 1], bloch: [[0, 0, -1] as [number, number, number]] };
const common = ['Choose Run Simulation. Each shot prepares the circuit afresh and measures once at the end.', 'Choose Explore steps. Inspect the initial state and every subsequent step with Next step. Open Step statevector to see amplitudes.', 'Choose Collect experiment & return. Back in the lesson, compare your prediction and answer the observation question.'];
const measurementExperiments: ExperimentDefinition[] = [
  { id: 'empty', title: 'An empty circuit', numQubits: 1, gates: [], prediction: predict('empty-p', 'With one qubit initialized in |0⟩ and no gates, what will the ideal outcomes be?', 0),
    instructions: ['Leave q0 empty: do not place any gate. The wire represents one qubit prepared in |0⟩.', ...common],
    observations: ['The initial state is also the final state: there are no gates. The amplitude of |0⟩ is 1, so measuring gives 0 with certainty.'], expected: [zero] },
  { id: 'x', title: 'Prepare one with X', numQubits: 1, gates: [{ type: 'x', target: 0 }], prediction: predict('x-p', 'Starting from |0⟩, what do you predict after X on q0?', 2),
    instructions: ['Select X in the gate palette, then the + cell on q0 at step 1. Use exactly one X on one qubit.', ...common],
    observations: ['Before X, |0⟩ has amplitude 1. Initialization gives a known starting point.', 'X swaps the two amplitudes. The amplitude of |1⟩ is now 1 and every ideal reading is 1.'], expected: [zero, one] },
  { id: 'h', title: 'Equal chances with H', numQubits: 1, gates: [{ type: 'h', target: 0 }], prediction: predict('h-p', 'H makes equal amplitude magnitudes from |0⟩. What ideal outcomes do you predict?', 1),
    instructions: ['Start with the empty q0 wire. Select H, then the + cell on q0 at step 1. Use one H and no other gates.', ...common],
    observations: ['Before H, a reading would certainly give 0.', 'H makes both amplitudes approximately 0.7071. Squaring either gives 0.5: each outcome has a 50% chance. This state is called a superposition.'], expected: [zero, plus] },
];
const phaseExperiments: ExperimentDefinition[] = [
  { id: 'hh', title: 'H → H', numQubits: 1, gates: [{ type: 'h', target: 0 }, { type: 'h', target: 0 }], prediction: predict('hh-p', 'With no measurement between them, what will two H gates do to |0⟩?', 0),
    instructions: ['Select H and place it on q0 at step 1. Select H again and place it on q0 at step 2. Both operations happen before measurement.', ...common],
    observations: ['The starting amplitudes are 1 for |0⟩ and 0 for |1⟩.', 'The first H produces equal positive amplitudes. Both ideal probabilities are 50%.', 'The second H adds the contributions toward |0⟩ and cancels those toward |1⟩. All ideal readings return 0.'], expected: [zero, plus, zero] },
  { id: 'hzh', title: 'H → Z → H', numQubits: 1, gates: [{ type: 'h', target: 0 }, { type: 'z', target: 0 }, { type: 'h', target: 0 }], prediction: predict('hzh-p', 'What changes if Z goes between the two H gates, starting in |0⟩?', 2),
    instructions: ['Place H on q0 at step 1, Z on q0 at step 2, and H on q0 at step 3. This exercise has its own empty draft.', 'To modify two existing H gates, select Z, open Add gate with form, set Insert position to Before step 2, then choose Add gate. Check the left-to-right order is H, Z, H.', ...common],
    observations: ['The qubit starts in |0⟩.', 'After H, both amplitudes are positive and approximately 0.7071.', 'Z changes the |1⟩ amplitude to approximately −0.7071. The probabilities stay 50/50; the Bloch direction changes from +X to −X.', 'The final H cancels the |0⟩ contributions and adds the |1⟩ contributions. The final ideal reading is always 1.'], expected: [zero, plus, minus, one] },
];
const bellExperiment: ExperimentDefinition = {
  id: 'bell', title: 'Build a Bell state', numQubits: 2, gates: [{ type: 'h', target: 0 }, { type: 'cx', target: 1, control: 0 }],
  prediction: predict('bell-p', 'H on q0 creates 00 and 01 components. After CX with control q0 and target q1, which pairs do you predict?', 1, true),
  instructions: ['Start with two empty wires, q0 and q1. Both start in |0⟩, so the pair is |00⟩.', 'Select H and place it on q0 at step 1.', 'Select CX. At step 2 select q0 first (control), then q1 (target) in the same column. The dot is the control and the ⊕ is the target.', ...common, 'In the Explorer, inspect both q0 and q1 using Inspect q0 / Inspect q1. On a narrow screen, choose Qubit sphere. Compare the final purity and vector length with the earlier steps.'],
  observations: ['Step 0: the joint state is |00⟩. Both individual qubits are pure and point toward +Z.', 'Step 1: H on q0 gives equal amplitudes for |00⟩ and |01⟩. q0 points along +X and q1 still points along +Z. Both are individually pure.', 'Step 2: CX leaves |00⟩ alone and moves the |01⟩ component to |11⟩. The joint state is a pure Bell state. Each qubit by itself is maximally mixed, with purity 0.5 and a vector at the center.'],
  expected: [
    { amplitudes: [1, 0, 0, 0], bloch: [[0, 0, 1], [0, 0, 1]] },
    { amplitudes: [a, a, 0, 0], bloch: [[1, 0, 0], [0, 0, 1]] },
    { amplitudes: [a, 0, 0, a], bloch: [[0, 0, 0], [0, 0, 0]] },
  ],
};

export const foundations: Record<FoundationId, FoundationLesson> = {
  measurement: {
    id: 'measurement', number: '01', title: 'Qubits and measurement', description: 'From a yes-or-no answer to your first quantum reading. Build three small experiments and learn what their results mean.',
    outcomes: ['Explain bits, qubits, and basis states', 'Prepare |0⟩ and |1⟩ using empty and X circuits', 'Distinguish ideal probabilities from sampled counts'], experiments: measurementExperiments,
    next: { href: '/learn/superposition', title: 'Superposition & the Hadamard gate' },
    sections: [
      { title: 'Information starts with a choice', paragraphs: ['Information helps us distinguish possibilities: is a door open or closed? A classical bit is one recorded choice between two labels, 0 and 1. We decide what those labels mean; 1 might mean “open”.', 'A bit can be stored using a physical device with two distinguishable conditions. The label is the information; the device is how we store it. Two bits record a pair such as 01.'], visual: 'bit', check: question('information', 'If 1 means “open”, what information does a stored bit of 0 represent?', ['The door is closed.', 'The door is both open and closed.', 'The device has no information.'], 0, 'The labels stand for two agreed alternatives. Here 0 records “closed”.') },
      { title: 'Meet a qubit', paragraphs: ['A qubit is a quantum system used to carry information. You do not need to know how the hardware is made to learn its rules. We describe its state: the mathematical information needed to predict what operations and readings will do.', 'The two reference states |0⟩ and |1⟩ are called computational basis states. Read |0⟩ as “state zero”. The brackets mark a quantum state; they are not extra bits. Measuring these states in this basis gives 0 and 1 respectively, with certainty.', 'Other qubit states need two amplitudes, one for each basis state. An amplitude is a number used to calculate probabilities and how later operations combine contributions. A qubit is not simply a classical bit with a hidden value: these contributions can reinforce or cancel, as you will test in the next lessons.'], visual: 'basis', check: question('qubit', 'What does |1⟩ mean here?', ['Two readable bits.', 'The basis state that gives 1 with certainty in this measurement.', 'A classical value we cannot know.'], 1, 'The ket |1⟩ names a quantum basis state. Its computational-basis reading is certainly 1.') },
      { title: 'Try a circuit with no gates', paragraphs: ['A circuit is an ordered set of operations on qubits. A line, or wire, tracks one qubit; q0 means qubit number zero. Initialization means preparing a known starting state. In this Lab every fresh run starts in |0⟩.', 'A gate is an operation that changes the quantum state. With no gates, nothing changes between initialization and the final measurement. Make your prediction, then test that baseline.', 'Our simulator uses an ideal model: no hardware noise or imperfect gates. An ideal probability is the chance calculated from that model’s quantum state.'], experiment: 'empty', check: question('empty-observation', 'Why did your empty circuit produce only zeros?', ['No gates changed the initialized |0⟩ state.', 'The simulator skipped measurement.', 'Every qubit always reads zero.'], 0, 'The circuit was executed and measured. With no gates, the initialized basis state stayed |0⟩.') },
      { title: 'Prepare one with X', paragraphs: ['The X gate swaps the two basis states: it sends |0⟩ to |1⟩ and |1⟩ to |0⟩. Starting in zero, X prepares a state whose measurement will give one.', 'You will place the gate yourself. The measurement happens automatically after the circuit; you do not add a measurement gate.'], equation: { notation: 'X|0⟩ = |1⟩', explanation: 'In words: applying X to state zero produces state one. Read the operation before the state as “apply this operation to this state”.' }, experiment: 'x', check: question('x-observation', 'Your X experiment changed which part of the process?', ['It changed the meaning of the label 1.', 'It changed the state before measurement.', 'It changed how many basis labels exist.'], 1, 'X changes the prepared state. The reading still uses the same labels 0 and 1.') },
      { title: 'What a measurement tells you', paragraphs: ['Measurement is an interaction that produces a classical record. In this app the computational basis is the reading choice: the possible records are 0 and 1 for each qubit. One reading gives one outcome, not the whole list of amplitudes.', 'For a qubit described by one statevector, write α|0⟩ + β|1⟩. The Greek letters alpha (α) and beta (β) name the two amplitudes. Their squared magnitudes give the two probabilities. Magnitude means the size of a number, ignoring its sign; for example, both +0.5 and −0.5 have magnitude 0.5.', 'An ideal computational-basis measurement also leaves the qubit in the basis state matching the recorded outcome: |0⟩ after zero or |1⟩ after one. This change is often called collapse. Measuring again immediately, with no new gates, gives the same result. Each Lab shot instead prepares the starting state afresh.', 'The State Explorer knows the mathematical state because it calculates the circuit. A physical measurement cannot print out that statevector from a single qubit. The Lab displays states before measurement, not a sequence of collapsed states.'], equation: { notation: 'P(0) = |α|²     P(1) = |β|²', explanation: 'P means probability. The vertical bars mean magnitude, and the raised 2 means square it: multiply the magnitude by itself. The two probabilities total 1, meaning 100%.' }, check: question('measurement', 'What does one computational-basis measurement return?', ['The complete statevector.', 'One classical outcome, 0 or 1.', 'Both amplitudes as two readings.'], 1, 'One shot produces one classical outcome per qubit. The simulator’s state display is extra mathematical access, not a measurement result.') },
      { title: 'Create equal chances with H', paragraphs: ['H, the Hadamard gate, creates equal positive amplitudes when applied to |0⟩. The resulting state is a superposition: both basis components contribute to the state.', 'Each amplitude is 1/√2, approximately 0.7071. This is the positive number whose square is 1/2. Each ideal probability is therefore 50%. H follows a fixed rule; the random outcome appears when we measure.'], experiment: 'h', check: question('h-observation', 'If your H circuit has 50% ideal probability for each outcome, must 1,024 shots be exactly 512 of each?', ['Yes, that is what 50% means.', 'No, finite sampled counts can fluctuate.'], 1, 'The probabilities specify chances. A finite batch of independent readings need not split exactly in half.') },
      { title: 'Chances and actual counts', paragraphs: ['An ideal probability comes from the state in the noiseless model. A sampled count records how often an outcome appeared in actual simulator readings. A shot means preparing the starting state, applying all gates, and measuring once.', 'A fair coin is a useful analogy for fluctuations in the final readings. It does not model the qubit state or the H gate: a quantum state also has amplitudes that can interfere.', 'The Lab fixes the random seed to make a run reproducible. A seed is a number that starts the simulator’s sampling sequence. Repeating the same circuit, shots, and seed reproduces counts. Different random samples can give different counts; ideal probabilities stay the same. More shots tend to give closer proportions, without a guarantee of an exact split.'], visual: 'shots', review: 'h', check: question('counts', 'Which explanation fits 537 zeros and 487 ones in a hypothetical 1,024-shot 50/50 experiment?', ['The gate must be broken.', 'This is possible sampling variation; ideal chances can still be equal.', 'The ideal probability of zero is exactly 537/1024.'], 1, 'Counts describe a finite sample. Their proportions estimate probabilities but do not redefine the state’s ideal probabilities.') },
      { title: 'Check your understanding', paragraphs: ['Explain the process to yourself: prepare a state, apply gates, then read one outcome per shot. Use that story to answer the questions below.'] },
    ],
    quiz: [
      question('m-q1', 'How is a general qubit state different from an unknown classical bit?', ['Amplitudes can combine in later operations.', 'A single measurement reveals two classical values.', 'There is no difference.'], 0, 'Amplitudes carry information about interference, beyond probabilities for an unknown classical value.'),
      question('m-q2', 'Which circuit prepares |1⟩ from the Lab’s initial |0⟩?', ['No gates.', 'One X on q0.', 'One H on q0.'], 1, 'X swaps the two basis states, so a final reading is certainly 1.'),
      question('m-q3', 'What happens afresh on each shot?', ['Only the same qubit is read again without preparation.', 'The counts are copied from ideal probabilities.', 'Initialize, apply all gates, and measure once.'], 2, 'Every shot repeats the full preparation and circuit before the final reading.'),
      question('m-q4', 'An amplitude is −0.5. What probability does it contribute?', ['−50%.', '25%.', '50%.'], 1, 'Its magnitude is 0.5; squaring gives 0.25, or 25%. Probabilities cannot be negative.'),
      question('m-q5', 'Why can H counts vary between different random samples?', ['Finite sampling fluctuates even when ideal chances stay 50/50.', 'H uses a different rule every time.', 'A statevector is a list of sampled counts.'], 0, 'Sampling introduces variation in counts. Replaying the same fixed seed reproduces one such sample.'),
    ],
  },
  phase: {
    id: 'phase', number: '03', title: 'Phase and interference', description: 'The same chances can hide different states. Follow the signs of amplitudes and discover how a final H reveals the difference.',
    outcomes: ['Distinguish relative phase from an overall sign', 'Build and compare H → H and H → Z → H', 'Explain reinforcement and cancellation of amplitudes'], experiments: phaseExperiments,
    next: { href: '/learn/entanglement', title: 'Entanglement and Bell states' },
    sections: [
      { title: 'Look beyond probabilities', paragraphs: ['A qubit has two basis states, |0⟩ and |1⟩. An amplitude is the number attached to each basis component. Squaring its magnitude gives that component’s measurement probability. A statevector is simply the ordered list of these amplitudes.', 'Positive and negative numbers have the same squared magnitude: (+0.7071)² and (−0.7071)² are both approximately 0.5. Probability bars can therefore look identical for different amplitude lists.', 'Phase describes how amplitudes are oriented relative to each other. General phases need complex numbers, which have real and imaginary parts. Here all imaginary parts are zero, so matching versus opposite signs is enough. Opposite signs mean a relative phase difference of half a turn, also called π radians.'], visual: 'signs', check: question('signs', 'Two amplitudes are +1/√2 and −1/√2. What are their probabilities?', ['One positive and one negative probability.', '50% for each.', '100% for each.'], 1, 'Signs disappear when magnitudes are squared. Both squared magnitudes are 1/2.') },
      { title: 'Meet the Z gate', paragraphs: ['Z leaves the |0⟩ amplitude alone and reverses the sign of the |1⟩ amplitude. It does not exchange the labels 0 and 1. Unlike X, it does not swap the amplitudes.', 'On the basis state |0⟩, Z has no effect. On |1⟩, Z produces −|1⟩. That minus sign is a change in the mathematical representation, but this state still gives 1 with certainty. The next section explains why.'], equation: { notation: 'Z(a|0⟩ + b|1⟩) = a|0⟩ − b|1⟩', explanation: 'Here a and b name the two amplitudes. Z keeps a and multiplies b by −1. Applying it to a positive b makes b negative; applying it to a negative b makes b positive.' }, check: question('z', 'Starting with two positive equal amplitudes, what does Z change immediately?', ['The sign of the |1⟩ amplitude, while both probabilities stay equal.', 'It makes the outcome 1 certain.', 'It measures the qubit.'], 0, 'Z flips one amplitude’s sign. Its squared magnitude is unchanged, so immediate computational-basis probabilities are unchanged.') },
      { title: 'Global or relative?', paragraphs: ['A global phase acts on the whole state. A global minus sign reverses every amplitude together, leaving their relationship the same. Every measurement prediction stays the same, including after any identical later gate sequence.', 'A relative phase changes the relationship between components. Flipping just one of two nonzero amplitudes creates a different state even if its immediate probabilities match.', 'Why is −|1⟩ only a global change? |1⟩ has amplitudes (0, 1); reversing both gives (0, −1), because negative zero is still zero. There is no second nonzero amplitude for a relative sign to compare with.'], visual: 'global', check: question('global', 'Which change is only a global minus sign?', ['(+a, +a) becomes (+a, −a).', '(+a, +a) becomes (−a, −a).', 'The probability of 1 changes from 0 to 1.'], 1, 'Both amplitudes reverse together. Their relative sign is unchanged, so all physical predictions remain the same.'), detail: { title: 'Optional: why later gates cannot reveal a global minus', text: 'Gates combine amplitudes linearly: applying the same gate to a whole state multiplied by −1 gives the original output multiplied by −1. Squared magnitudes still agree. This applies to a phase on the entire state; changing only one component is different.' } },
      { title: 'Build H → H', paragraphs: ['H sends |0⟩ to equal positive amplitudes. It sends |1⟩ to equal magnitudes with a minus sign on the |1⟩ component. When both input components are present, their contributions combine.', 'Make a prediction before using that rule twice. There is no measurement between the H gates: the second H acts on the full superposition.'], experiment: 'hh', check: question('hh-observation', 'Why does your second H give only zero?', ['Two random bits average to zero.', 'Contributions to the one amplitude cancel before measurement.', 'The second H reads the first gate.'], 1, 'The gate combines amplitudes, not sampled bits. The one contributions cancel and the zero contributions add.') },
      { title: 'Build H → Z → H', paragraphs: ['Now change the relative sign between the two H gates. Z changes the state after the first H without changing its immediate 50/50 probabilities.', 'Predict the final reading, then build H, Z, H in that order on q0. Inspect all four snapshots, including the starting state. Pay special attention to the sign after Z and the probabilities after the final H.'], experiment: 'hzh', check: question('hzh-observation', 'At which step did probabilities change from 50/50 to always one?', ['At Z: a negative amplitude is a negative chance.', 'At the final H, when the changed contributions combined.', 'At the initial preparation.'], 1, 'Z changed a relative sign. The final H converted that difference into a different measurement distribution.') },
      { title: 'Follow the interference', paragraphs: ['Interference means combining amplitude contributions. Contributions with matching signs can reinforce: constructive interference. Opposing contributions can cancel: destructive interference. Add amplitudes first, then square the resulting magnitude to get a probability.', 'Think of signed arrows: equal arrows pointing the same way add; equal arrows pointing opposite ways cancel. This is a picture of the arithmetic, not two physical paths or two classical qubits hiding inside one qubit.'], visual: 'interference', equation: { notation: 'After H:  zero = (a + b)/√2,  one = (a − b)/√2', explanation: 'a and b are the incoming amplitudes for zero and one. H adds them for the new zero amplitude and subtracts them for the new one amplitude, then divides each by √2. For H → H the inputs to the second H match, so the subtraction is zero. After Z they oppose, so the addition is zero instead.' }, check: question('interference', 'In H → Z → H, which contributions cancel at the final H?', ['The contributions to the |0⟩ amplitude.', 'The probabilities for both outcomes.', 'The sampled counts.'], 0, 'The inputs are +1/√2 and −1/√2. Their sum is zero; their difference, divided by √2, is one.'), detail: { title: 'Optional: the same rule as a matrix', text: 'A matrix is a grid that packages a linear rule. H = (1/√2) [[1, 1], [1, −1]]. Multiply the first row by the input column (a, b) to get (a+b)/√2; the second row gives (a−b)/√2. Z = [[1, 0], [0, −1]] keeps a and reverses b. The grid adds no new prerequisite: it records the rules you just used.' } },
      { title: 'Explain your observation', paragraphs: ['Your two experiments began in the same state and used the same first and last gates. Inserting Z changed the relative sign between the components, and that changed which contributions cancelled at the last H.', 'Equal probability bars after H and after H → Z do not mean identical quantum states. The statevector and Bloch map expose that difference in this simulator. The +X and −X labels on the sphere are state directions; they do not say you placed X gates.'], review: 'hzh', check: question('explain-phase', 'Which explanation connects all three gates in H → Z → H?', ['H chooses a hidden bit, Z reads it, and H copies it.', 'H creates two contributions; Z reverses one sign; the final H cancels zero and reinforces one.', 'Z alone always flips a measured zero to one.'], 1, 'The experiment reveals relative phase through later interference. The full circuit has the same action as X, although Z by itself is not X.') },
      { title: 'Check your understanding', paragraphs: ['Use both experiments as evidence. You can reopen their sections to compare the amplitudes and probabilities before submitting.'] },
    ],
    quiz: [
      question('p-q1', 'Can identical computational-basis probabilities describe different pure states?', ['Yes, relative amplitude signs can differ.', 'No, probabilities contain all state information.', 'Only if counts are wrong.'], 0, 'Opposite and matching relative signs give the same immediate probabilities but can interfere differently later.'),
      question('p-q2', 'What does Z do to |1⟩?', ['Makes |0⟩.', 'Makes −|1⟩, with the same physical predictions.', 'Measures 1.'], 1, 'For this basis state the minus is global. It changes no physical prediction.'),
      question('p-q3', 'Why does H → Z → H produce |1⟩ from |0⟩?', ['Probabilities cancel each other.', 'Z forces a measurement.', 'The final H adds the one contributions and cancels the zero contributions.'], 2, 'The relative minus from Z changes the amplitude addition at the last H.'),
      question('p-q4', 'If every amplitude gets the same minus sign, what changes physically?', ['Every final bit flips.', 'No measurement prediction changes under identical later operations.', 'All probabilities become negative.'], 1, 'A global minus preserves relative phase and squared magnitudes.'),
      question('p-q5', 'What is the correct order for finding a probability after interference?', ['Add amplitude contributions, then square the magnitude.', 'Square each contribution, then cancel the probabilities.', 'Average the gate names.'], 0, 'Interference acts at the amplitude level before a probability is calculated.'),
    ],
  },
  entanglement: {
    id: 'entanglement', number: '04', title: 'Entanglement and Bell states', description: 'Build a shared two-qubit state. Learn what the pair reveals, what each qubit leaves out, and why correlation alone is not the whole story.',
    outcomes: ['Read two-qubit labels in q1 q0 order', 'Build H(q0) → CX(q0 → q1) and inspect three trace steps', 'Explain a pure joint Bell state with maximally mixed individual states'], experiments: [bellExperiment],
    next: { href: '/lab?workspace=free', title: 'Keep exploring in the Circuit Lab' },
    sections: [
      { title: 'Four possible pairs', paragraphs: ['A computational basis state describes a definite string of measurement results. One qubit has two such labels, 0 and 1. Two qubits have four: 00, 01, 10, and 11. Each label records one result for each qubit.', 'A two-qubit statevector lists four amplitudes in that order. Each amplitude belongs to the whole pair, not to one qubit alone. Squared magnitudes give probabilities for the corresponding pair. A general state can have several contributing pairs.'], visual: 'pairs', check: question('pairs', 'How many computational basis labels are needed for two qubits?', ['Two: 0 and 1.', 'Four: 00, 01, 10, 11.', 'One label per gate.'], 1, 'Each of the two outcomes for one qubit can pair with either outcome for the other: 2 × 2 = 4.') },
      { title: 'Read the bit order', paragraphs: ['The Lab writes labels in q[n−1]…q[0] order: n means the number of qubits, and q0 is always the rightmost bit. For two qubits, read q1 on the left and q0 on the right. This order is a notation choice, not a physical property.', '|01⟩ therefore means q1 is zero and q0 is one. |10⟩ means q1 is one and q0 is zero. The top wire is q0, but its reading appears on the right of the label. X on q0 starting from |00⟩ produces |01⟩.'], visual: 'pairs', check: question('order', 'Starting at |00⟩, X on q0 gives which label in this app?', ['|10⟩', '|01⟩', '|11⟩'], 1, 'q0 is the rightmost bit, so changing only q0 from zero to one gives |01⟩.') },
      { title: 'A controlled change', paragraphs: ['Controlled-X, written CX, uses two different qubits. The control decides which basis components get an X on the target. If the control bit is 0, the target stays the same; if it is 1, the target flips.', 'With control q0 and target q1, |00⟩ stays |00⟩ and |01⟩ becomes |11⟩. The rule acts on each component of a superposition while preserving its amplitude. CX does not measure the control or choose a random branch.', 'The circuit symbol uses a dot for the control and a circled plus for the target. Read the arrow q0 → q1 as “q0 controls a flip on q1”.'], visual: 'cx', check: question('cx', 'What does CX(q0 → q1) do to |10⟩?', ['Leaves |10⟩ unchanged because q0 is 0.', 'Changes it to |11⟩.', 'Measures q1.'], 0, 'In |10⟩ the rightmost bit, q0, is zero. The target q1 is therefore left alone.') },
      { title: 'Predict and build a Bell state', paragraphs: ['Start in |00⟩. H on q0 makes equal positive amplitudes for |00⟩ and |01⟩; q1 has not changed yet. CX(q0 → q1) then leaves the first component alone and changes the second to |11⟩.', 'The result is a Bell state: a particular entangled state of two qubits. Entangled means the joint pure state cannot be written as one independent pure state for each qubit. We will connect this definition to your observations after building.'], equation: { notation: '(|00⟩ + |11⟩)/√2', explanation: 'This names one joint state with equal positive amplitudes, 1/√2, for the pairs 00 and 11. It does not mean either qubit individually holds this two-qubit expression. Squaring each magnitude gives 1/2, so each of those pairs has 50% ideal probability.' }, experiment: 'bell', check: question('bell-observation', 'After CX in your trace, where did the |01⟩ component go?', ['It disappeared because measurement happened.', 'It became |11⟩, with its amplitude preserved.', 'It became two independent random bits.'], 1, 'The control q0 was 1 in that component, so CX flipped q1 from 0 to 1. The |00⟩ component stayed unchanged.') },
      { title: 'Read the joint state', paragraphs: ['Joint means describing the pair together. Your final statevector has nonzero amplitudes at 00 and 11, each about 0.7071. The other amplitudes are zero. The ideal pair probabilities are 50% for 00 and 11, and 0% for 01 and 10.', 'The two recorded bits always agree in this ideal experiment, even though either bit alone is equally likely to be 0 or 1. Sampled counts need not split exactly in half. This agreement is called correlation.', 'A pure state is a state that can be described by a single statevector, up to a global phase. Pure does not mean a certain measurement outcome: the Bell state is pure even though its outcomes vary. Our initialized state stays jointly pure through these noiseless gates, before measurement.'], review: 'bell', visual: 'bell', check: question('joint', 'Does a pure joint state require one certain computational-basis result?', ['Yes, pure means only zeros.', 'No, a pure Bell state has two possible correlated results.'], 1, 'Purity describes the state, not whether this measurement is deterministic. A single Bell statevector predicts both 00 and 11.') },
      { title: 'Look at one qubit', paragraphs: ['A reduced state describes only one part of a larger system, when the other part is ignored. Reducing is a mathematical view; we do not measure or physically remove the other qubit. A mixed state cannot be described by a single pure-state vector for that part.', 'For either qubit in your Bell state, the reduced state is maximally mixed: it has equal probabilities in every single-qubit measurement basis and no preferred direction. This app measures in the computational basis; the reduced-state mathematics also lets us infer the statement about other bases.', 'The Bloch sphere maps a single-qubit state. Pure states lie on its surface; mixed states lie inside. A maximally mixed state is at the center, with vector (0, 0, 0). That does not mean the qubit is absent or the simulator failed.', 'Purity is a number that quantifies this distinction: for one qubit it ranges from 0.5 (maximally mixed) to 1 (pure). The pair’s purity is 1, while q0 and q1 each have purity 0.5. In contrast, after only H the q0 superposition is pure and points along +X, even though it also has 50/50 computational-basis probabilities.'], visual: 'mixed', review: 'bell', check: question('reduced', 'At the final Bell step, why are both individual Bloch vectors centered?', ['Each qubit is maximally mixed when its partner is ignored; the joint state remains pure.', 'Both qubits have been erased.', 'Each qubit is a pure 50/50 superposition on the surface.'], 0, 'The local views lose information about the shared state. They cannot be replaced by two independent pure superpositions.'), detail: { title: 'Optional: reading the density matrix and purity', text: 'A density matrix can describe pure and mixed states. Each Bell qubit has matrix [[0.5, 0], [0, 0.5]] in the 0,1 basis: equal diagonal probabilities and zero off-diagonal coherence. Purity is Tr(ρ²), read “trace of rho squared”: multiply the matrix by itself and add the diagonal. Here 0.25 + 0.25 = 0.5. For the joint Bell state that number is 1. The Lab calculates reduced matrices from the joint state using a partial trace.' } },
      { title: 'More than matching bits', paragraphs: ['Classical correlation is easy to make: flip a fair coin and write the same result on two cards. The pair is always 00 or 11. Those counts alone do not prove entanglement. The card example has classical uncertainty about which definite pair was prepared.', 'The Bell state is a coherent superposition: its components retain a relative phase that later gates can reveal. The classical mixture of 00 and 11 has no such coherence. Your known gate preparation and the real joint statevector establish entanglement in this ideal model; this is not a Bell-inequality test on physical hardware.', 'Why can it not be two independent pure qubits? To allow 00 and 11, each independent qubit would need both zero and one components. Multiplying those independent descriptions would also produce 01 and 10. Those components are absent in the Bell state, so no such factorization works.', 'The centered spheres alone are not proof: a classical 50/50 mixture of 00 and 11 has the same reduced states. It is the full joint state that distinguishes them. Correlation also does not let one observer choose the other’s random outcome or send a message instantly.'], check: question('correlation', 'What distinguishes your ideal Bell preparation from two matching classical cards?', ['Matching 00/11 counts alone.', 'The coherent joint state, which cannot factor into two pure qubit states.', 'A zero Bloch vector alone.'], 1, 'Counts and local mixed states are not enough by themselves. The known circuit and coherent joint statevector provide the additional information in this simulator.') },
      { title: 'Check your understanding', paragraphs: ['Explain the journey from two separate zeros, through a superposition on q0, to a shared Bell state. Keep joint and individual descriptions distinct in your answers.'] },
    ],
    quiz: [
      question('e-q1', 'In the label |01⟩, which qubit is 1?', ['q1, the left bit.', 'q0, the right bit.', 'Both qubits.'], 1, 'The app labels two-qubit states in q1 q0 order.'),
      question('e-q2', 'Which circuit makes the Bell state from |00⟩ here?', ['H on q0, then CX with control q0 and target q1.', 'CX on |00⟩, then stop.', 'One X on each qubit.'], 0, 'H creates the 00 and 01 components; CX maps 01 to 11 while preserving 00.'),
      question('e-q3', 'What are the ideal final pair probabilities?', ['25% for all four labels.', '100% for 11.', '50% for 00 and 11, zero for 01 and 10.'], 2, 'Only 00 and 11 have nonzero amplitudes, each with squared magnitude 1/2.'),
      question('e-q4', 'Which purity statement describes the Bell state before measurement?', ['The pair and both qubits separately are all pure.', 'The joint state is pure; each reduced qubit is maximally mixed with purity 0.5.', 'The pair is mixed because its readings vary.'], 1, 'A pure entangled joint state can have mixed reduced states. The individual Bloch vectors sit at the center.'),
      question('e-q5', 'Do matching 00 and 11 counts alone establish entanglement?', ['Yes, agreement always means entanglement.', 'No, classical correlation can have the same counts.', 'Yes, if we use enough shots.'], 1, 'A classical mixture can reproduce those counts. Entanglement concerns the joint quantum state; other measurement settings would be needed for a suitable hardware test.'),
    ],
  },
};

export const foundationIds = Object.keys(foundations) as FoundationId[];
export const isFoundationId = (id: string): id is FoundationId => foundationIds.includes(id as FoundationId);
export const getExperiment = (id: FoundationId, experiment: string) => foundations[id].experiments.find((item) => item.id === experiment);
export const experimentHref = (id: FoundationId, experiment: string) => `/lab?lesson=${id}&experiment=${experiment}`;
